version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      # 민감하지 않거나 .env 파일에서 직접 로드하지 않을 변수들을 여기에 유지합니다.
      # GOOGLE_REDIRECT_URI와 APP_FRONTEND_URL은 민감하진 않지만,
      # 배포 환경에 따라 변경될 수 있으므로 .env로 옮기는 것이 좋습니다.
      # 여기서는 명확성을 위해 일단 그대로 둡니다.
      - GOOGLE_REDIRECT_URI=http://ec2-13-125-31-40.ap-northeast-2.compute.amazonaws.com/api/v1/auth/google/callback
      - APP_FRONTEND_URL=http://ec2-13-125-31-40.ap-northeast-2.compute.amazonaws.com

      # 아래 변수들은 .env 파일에서 로드됩니다.
      # 실제 값은 .env 파일에만 존재하고 Git에는 커밋되지 않습니다.
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}

    env_file: # 이 서비스가 .env 파일을 읽도록 지시합니다.
      - .env

    volumes:
      - ./app:/app/app
      - ./migrations:/app/migrations

  db:
    image: mysql:8.0
    restart: always
    environment:
      # MySQL 데이터베이스의 root 비밀번호와 데이터베이스 이름은 .env에서 로드됩니다.
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - local_db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  local_db: