version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Google 및 Naver 리디렉션 URI 및 앱 프론트엔드 URL
      - GOOGLE_REDIRECT_URI=http://ec2-13-125-31-40.ap-northeast-2.compute.amazonaws.com/api/v1/auth/google/callback
      - NAVER_REDIRECT_URI=http://ec2-13-125-31-40.ap-northeast-2.compute.amazonaws.com/api/v1/auth/naver/callback
      - APP_FRONTEND_URL=http://ec2-13-125-31-40.ap-northeast-2.compute.amazonaws.com

      # 아래 변수들은 .env 파일에서 로드됩니다.
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}

    env_file: # 이 서비스가 .env 파일을 읽도록 지시합니다.
      - .env

    volumes:
      - ./app:/app/app
      - ./migrations:/app/migrations

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - local_db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  local_db: