[project]
name = "oz-mini-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.2"
dependencies = [
    "alembic>=1.16.1",
    "fastapi[standard]>=0.115.12",
    "pydantic>=2.11.5",
    "pymysql>=1.1.1",
    "python-dotenv>=1.1.0",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "ruff>=0.11.13",
]
