"""create user table2

Revision ID: 188c77f79f89
Revises: 9fe97285482f
Create Date: 2025-06-09 19:34:04.170653

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "188c77f79f89"
down_revision: Union[str, None] = "9fe97285482f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
