"""initial

Revision ID: 3b16cd4ef283
Revises:
Create Date: 2025-06-11 18:10:53.447781

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "3b16cd4ef283"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
